name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-22.04
            args: ""
          - platform: windows-latest
            args: ""
          - platform: macos-latest
            args: "--target x86_64-apple-darwin"
          - platform: macos-latest
            args: "--target aarch64-apple-darwin"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Create Update JSON
        if: matrix.platform == 'windows-latest' && startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo '{
            "version": "v'${VERSION}'",
            "notes": "See the assets to download and install this version.",
            "pub_date": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'",
            "platforms": {
              "windows-x86_64": {
                "url": "https://github.com/KarnesTH/karncrypt/releases/download/v'${VERSION}'/karncrypt_'${VERSION}'_x64-setup.exe"
              },
              "linux-x86_64-debian": {
                "url": "https://github.com/KarnesTH/karncrypt/releases/download/v'${VERSION}'/karncrypt_'${VERSION}'_amd64.deb"
              },
              "linux-x86_64-redhat": {
                "url": "https://github.com/KarnesTH/karncrypt/releases/download/v'${VERSION}'/karncrypt-'${VERSION}'-1.x86_64.rpm"
              },
              "linux-x86_64": {
                "url": "https://github.com/KarnesTH/karncrypt/releases/download/v'${VERSION}'/karncrypt_'${VERSION}'_amd64.AppImage"
              },
              "darwin-x86_64": {
                "url": "https://github.com/KarnesTH/karncrypt/releases/download/v'${VERSION}'/karncrypt_'${VERSION}'_x64.dmg"
              },
              "darwin-aarch64": {
                "url": "https://github.com/KarnesTH/karncrypt/releases/download/v'${VERSION}'/karncrypt_'${VERSION}'_aarch64.dmg"
              }
            }
          }' > update.json

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__
          releaseName: "Release v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          args: ${{ matrix.args }}
          files: |
            update.json
