name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-22.04
            args: ""
          - platform: windows-latest
            args: ""
          - platform: macos-latest
            args: "--target x86_64-apple-darwin"
          - platform: macos-latest
            args: "--target aarch64-apple-darwin"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: |
            wasm32-unknown-unknown
            ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            libgdk3.0-cil-dev \
            libsqlcipher-dev \
            libsqlite3-dev \
            openssl \
            libssl-dev
          echo "SQLITE_CFLAGS=-fPIC" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=/usr/include/openssl" >> $GITHUB_ENV

      - name: Install Windows dependencies
        if: matrix.platform == 'windows-latest'
        shell: bash
        run: |
          vcpkg integrate install
          vcpkg install openssl:x64-windows-static
          vcpkg install sqlite3[core]:x64-windows-static
          echo "OPENSSL_DIR=C:\vcpkg\installed\x64-windows-static" >> $GITHUB_ENV
          echo "OPENSSL_STATIC=1" >> $GITHUB_ENV
          echo "VCPKGRS_DYNAMIC=1" >> $GITHUB_ENV
          echo "SQLITE3_LIB_DIR=C:\vcpkg\installed\x64-windows-static\lib" >> $GITHUB_ENV
          echo "SQLITE3_INCLUDE_DIR=C:\vcpkg\installed\x64-windows-static\include" >> $GITHUB_ENV
          echo "LIBSQLITE3_SYS_USE_PKG_CONFIG=0" >> $GITHUB_ENV

      - name: Install macOS dependencies
        if: matrix.platform == 'macos-latest'
        run: |
          brew update
          brew install openssl@3
          brew install sqlite3 sqlcipher

          if [[ "${{ matrix.args }}" == *"x86_64"* ]]; then
            echo "MACOSX_DEPLOYMENT_TARGET=10.13" >> $GITHUB_ENV
            echo "OPENSSL_LIB_DIR=/usr/local/opt/openssl@3/lib" >> $GITHUB_ENV
            echo "OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl@3/include" >> $GITHUB_ENV
          else
            echo "MACOSX_DEPLOYMENT_TARGET=11.0" >> $GITHUB_ENV
            echo "OPENSSL_LIB_DIR=/opt/homebrew/opt/openssl@3/lib" >> $GITHUB_ENV
            echo "OPENSSL_INCLUDE_DIR=/opt/homebrew/opt/openssl@3/include" >> $GITHUB_ENV
          fi

      - name: Install Trunk
        run: cargo install --locked trunk

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          OPENSSL_DIR: ${{ env.OPENSSL_DIR }}
          OPENSSL_LIB_DIR: ${{ env.OPENSSL_LIB_DIR }}
          OPENSSL_INCLUDE_DIR: ${{ env.OPENSSL_INCLUDE_DIR }}
          OPENSSL_STATIC: ${{ matrix.platform == 'windows-latest' && '1' || '' }}
          VCPKGRS_DYNAMIC: ${{ matrix.platform == 'windows-latest' && '1' || '' }}
          SQLITE3_LIB_DIR: ${{ env.SQLITE3_LIB_DIR }}
          SQLITE3_INCLUDE_DIR: ${{ env.SQLITE3_INCLUDE_DIR }}
          LIBSQLITE3_SYS_USE_PKG_CONFIG: ${{ env.LIBSQLITE3_SYS_USE_PKG_CONFIG }}
          SQLITE_CFLAGS: ${{ env.SQLITE_CFLAGS }}
          MACOSX_DEPLOYMENT_TARGET: ${{ env.MACOSX_DEPLOYMENT_TARGET }}
          PKG_CONFIG_PATH: ${{ matrix.platform == 'macos-latest' && '/usr/local/opt/openssl@3/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/sqlcipher/lib/pkgconfig' || '' }}
          OPENSSL_NO_VENDOR: ${{ matrix.platform == 'ubuntu-22.04' && '1' || '' }}
          SQLITE3_STATIC: ${{ matrix.platform == 'ubuntu-22.04' && '0' || '' }}
        with:
          tagName: v__VERSION__
          releaseName: "Release v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          args: ${{ matrix.args }}
