name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Install OpenSSL (Windows)
        if: matrix.platform == 'windows-latest'
        shell: bash
        run: |
          vcpkg integrate install
          vcpkg install openssl:x64-windows-static
          echo "OPENSSL_DIR=C:\vcpkg\installed\x64-windows-static" >> $env:GITHUB_ENV
          echo "OPENSSL_STATIC=1" >> $env:GITHUB_ENV
          echo "VCPKGRS_DYNAMIC=1" >> $env:GITHUB_ENV

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install Trunk
        run: cargo install --locked trunk

      - name: Install Tauri CLI
        run: cargo install tauri-cli --version "^2.0.0"

      - name: Build Release (Windows)
        if: matrix.platform == 'windows-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          OPENSSL_DIR: C:\vcpkg\installed\x64-windows-static
          OPENSSL_STATIC: 1
          VCPKGRS_DYNAMIC: 1
        run: |
          trunk build
          cargo tauri build

      - name: Build Release (Linux)
        if: matrix.platform == 'ubuntu-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        run: |
          trunk build
          cargo tauri build

      - name: Upload Linux Artifacts
        if: matrix.platform == 'ubuntu-latest' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            /home/runner/work/karncrypt/karncrypt/target/release/bundle/deb/karncrypt_0.1.0_amd64.deb
            /home/runner/work/karncrypt/karncrypt/target/release/bundle/rpm/karncrypt-0.1.0-1.x86_64.rpm
            /home/runner/work/karncrypt/karncrypt/target/release/bundle/appimage/karncrypt_0.1.0_amd64.AppImage

      - name: Upload Windows Artifacts
        if: matrix.platform == 'windows-latest' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            D:/a/karncrypt/karncrypt/target/release/bundle/msi/karncrypt_0.1.0_x64_de-DE.msi
            D:/a/karncrypt/karncrypt/target/release/bundle/nsis/karncrypt_0.1.0_x64-setup.exe
